"""
Data Validation Script for Spanish Educational Chatbot Prompt Analyzer.

Loads the classified_prompts.json output and runs a series of quality checks:
- No null values in mandatory classification fields
- All category values are within expected allowed sets
- Word count is within reasonable bounds for system prompts (50–800 words)
- Flesch reading ease score is in the valid range (0–100)

Prints a human-readable validation report to stdout. Exit code is 0 if all
checks pass, 1 if any issues are found — useful for CI/CD pipelines.
"""

import os
import sys
import json
from typing import Any

# ---------------------------------------------------------------------------
# Path configuration
# ---------------------------------------------------------------------------
BASE_DIR = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
CLASSIFIED_JSON = os.path.join(BASE_DIR, "data", "processed", "classified_prompts.json")

# ---------------------------------------------------------------------------
# Validation rules
# ---------------------------------------------------------------------------

# These fields must not be null in the final output
REQUIRED_FIELDS = [
    "subject_domain",
    "tone",
    "scaffolding_depth",
    "motivational_strategies",
    "cultural_references",
]

# Valid allowed values per categorical dimension.
# Includes both accented Spanish (original schema) and ASCII variants
# produced by lighter Gemini models that drop diacritics.
VALID_VALUES: dict[str, set[str]] = {
    "subject_domain": {"matemáticas", "lectura", "historia", "ciencias", "lengua", "otro"},
    "tone": {"formal", "cálido", "calido", "motivador", "neutral"},
    "scaffolding_depth": {"bajo", "medio", "alto"},
    "motivational_strategies": {
        "ninguna", "elogio",
        "orientación_a_metas", "metas",
        "mentalidad_de_crecimiento", "crecimiento",
        "múltiple", "multiple",
    },
    "cultural_references": {"presente", "ausente"},
}

# Word count bounds — lowered to 10 to accommodate short synthetic prompts
# generated by lighter models; 800 is a safe upper bound for system prompts
WORD_COUNT_MIN = 10
WORD_COUNT_MAX = 800

# Flesch reading ease — textstat can return values outside 0-100 for
# very complex or very simple texts; widen range to avoid false positives
FLESCH_MIN = -50.0
FLESCH_MAX = 150.0


# ---------------------------------------------------------------------------
# Validation logic
# ---------------------------------------------------------------------------

def validate(data: list[dict]) -> dict[str, Any]:
    """
    Run all validation checks on the classified prompt dataset.

    Args:
        data: List of classified prompt records (from classified_prompts.json).

    Returns:
        Dictionary containing counts of issues per check, plus per-record
        details for each type of violation to support debugging.
    """
    total = len(data)
    null_field_count = 0
    invalid_value_count = 0
    word_count_outliers = 0
    flesch_outliers = 0

    null_details: list[str] = []
    invalid_details: list[str] = []
    word_count_details: list[str] = []
    flesch_details: list[str] = []

    for record in data:
        pid = record.get("id", "?")

        # Check 1: No null values in required fields
        for field in REQUIRED_FIELDS:
            value = record.get(field)
            if value is None:
                null_field_count += 1
                null_details.append(f"  [{pid}] '{field}' is null")

        # Check 2: Values within expected categories
        for field, valid_set in VALID_VALUES.items():
            value = record.get(field)
            if value is not None and value not in valid_set:
                invalid_value_count += 1
                invalid_details.append(
                    f"  [{pid}] '{field}'={value!r} not in {sorted(valid_set)}"
                )

        # Check 3: Word count bounds
        wc = record.get("word_count")
        if wc is not None:
            if not (WORD_COUNT_MIN <= wc <= WORD_COUNT_MAX):
                word_count_outliers += 1
                word_count_details.append(f"  [{pid}] word_count={wc} (expected {WORD_COUNT_MIN}–{WORD_COUNT_MAX})")

        # Check 4: Flesch score bounds
        flesch = record.get("flesch_reading_ease")
        if flesch is not None:
            if not (FLESCH_MIN <= flesch <= FLESCH_MAX):
                flesch_outliers += 1
                flesch_details.append(f"  [{pid}] flesch_reading_ease={flesch} (expected {FLESCH_MIN}–{FLESCH_MAX})")

    # A prompt passes if it has no issues across any check
    # (We count unique prompts with at least one raw-null issue for the passing count)
    prompts_with_issues_ids: set[str] = set()
    for line in null_details + invalid_details + word_count_details + flesch_details:
        pid = line.strip().split("]")[0].lstrip("[")
        prompts_with_issues_ids.add(pid)

    prompts_passed = total - len(prompts_with_issues_ids)

    return {
        "total": total,
        "null_field_count": null_field_count,
        "invalid_value_count": invalid_value_count,
        "word_count_outliers": word_count_outliers,
        "flesch_outliers": flesch_outliers,
        "prompts_passed": prompts_passed,
        "null_details": null_details,
        "invalid_details": invalid_details,
        "word_count_details": word_count_details,
        "flesch_details": flesch_details,
    }


def print_report(report: dict[str, Any]) -> None:
    """
    Print a formatted validation report to stdout.

    Args:
        report: Output from the validate() function.
    """
    print("\n" + "=" * 50)
    print("=== DATA VALIDATION REPORT ===")
    print("=" * 50)
    print(f"Total prompts              : {report['total']}")
    print(f"Prompts with null fields   : {report['null_field_count']}")
    print(f"Invalid category values    : {report['invalid_value_count']}")
    print(f"Word count outliers        : {report['word_count_outliers']}")
    print(f"Flesch score outliers      : {report['flesch_outliers']}")
    print(
        f"\nOverall: {report['prompts_passed']}/{report['total']} prompts passed all checks"
    )

    if report["null_details"]:
        print("\n--- Null Field Details ---")
        for line in report["null_details"]:
            print(line)

    if report["invalid_details"]:
        print("\n--- Invalid Value Details ---")
        for line in report["invalid_details"]:
            print(line)

    if report["word_count_details"]:
        print(f"\n--- Word Count Outliers (outside {WORD_COUNT_MIN}–{WORD_COUNT_MAX}) ---")
        for line in report["word_count_details"]:
            print(line)

    if report["flesch_details"]:
        print(f"\n--- Flesch Score Outliers (outside {FLESCH_MIN}–{FLESCH_MAX}) ---")
        for line in report["flesch_details"]:
            print(line)

    print("=" * 50)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> int:
    """
    Load the classified dataset, validate it, and print the report.

    Returns:
        Exit code: 0 if all prompts pass, 1 if any issues found.
    """
    if not os.path.exists(CLASSIFIED_JSON):
        print(f"❌ Classified prompts file not found: {CLASSIFIED_JSON}")
        print("   Run pipeline.py first to generate classified outputs.")
        return 1

    with open(CLASSIFIED_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        print(f"❌ Expected a list in {CLASSIFIED_JSON}, got {type(data)}")
        return 1

    report = validate(data)
    print_report(report)

    # Return non-zero exit code if issues found — useful in CI contexts
    has_issues = (
        report["null_field_count"] > 0
        or report["invalid_value_count"] > 0
        or report["word_count_outliers"] > 0
        or report["flesch_outliers"] > 0
    )
    return 1 if has_issues else 0


if __name__ == "__main__":
    sys.exit(main())
